### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by stack72** [hatchery/dna-download_file#4]
If you are going to fork our (http://github.com/opentable/puppet-download_file) module and extend it, then please at least give some credit and update the LICENSE to reflect that it is no longer only our work

Alternatively, you can send a PR to the upstream repository and we will include the work

thanks

Paul

**Comment by DavidJFelix** [comment]
Fixed request in ca90bfdae8260f8012bcaccb362d04f25846377f

Please let me know if these changes are sufficient. Also, I did send a PR to the upstream repo; I haven't heard a peep about it for nearly two and a half months. See https://github.com/opentable/puppet-download_file/pull/16

I was originally developing this as a fork, but github does not credit work toward a fork in profile contribution activity unless it's merged upstream. Since I hadn't heard anything back, I assumed there was no desire to merge any new features or perhaps nobody maintained the module. You'll note that I'm still maintaining an active fork: https://github.com/hatchery/puppet-download_file but I'm not actively developing in that fork -- I develop here, then push working features to the forked repo and propose pull requests with that.
